CREATE DATABASE `thegame`;

DROP TABLE IF EXISTS `items`;
CREATE TABLE `items` {
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL DEFAULT '',

	PRIMARY KEY (`id`)
} ENGINE=MyISAM DEFAULT CHARSET=utf8;
